"""Initial migration

Revision ID: 4b3101582ce5
Revises: b83142477c27
Create Date: 2025-06-04 10:11:07.903098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b3101582ce5'
down_revision: Union[str, None] = 'b83142477c27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tasks', sa.Column('token', sa.String(), nullable=True))
    op.drop_index(op.f('ix_Tasks_email'), table_name='Tasks')
    op.create_index(op.f('ix_Tasks_token'), 'Tasks', ['token'], unique=True)
    op.drop_column('Tasks', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tasks', sa.Column('email', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_Tasks_token'), table_name='Tasks')
    op.create_index(op.f('ix_Tasks_email'), 'Tasks', ['email'], unique=1)
    op.drop_column('Tasks', 'token')
    # ### end Alembic commands ###
