"""Initial migration

Revision ID: b83142477c27
Revises: 0b479b2cae66
Create Date: 2025-06-04 04:32:22.368597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b83142477c27'
down_revision: Union[str, None] = '0b479b2cae66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tasks',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_Tasks_email'), 'Tasks', ['email'], unique=True)
    op.create_index(op.f('ix_Tasks_task_id'), 'Tasks', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Tasks_task_id'), table_name='Tasks')
    op.drop_index(op.f('ix_Tasks_email'), table_name='Tasks')
    op.drop_table('Tasks')
    # ### end Alembic commands ###
